import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/page";
import Footer from "@/components/Footer/page";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tejas's-Portfolio",
  description: "Generated by Tejas",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="relative w-full flex justify-center items-center">
          <Navbar className="text-xl  rounded-full border border-red-50" />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
